version: '3.8'

services:
  transcript-processor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
    ports:
      - "8099:8080"
    environment:
      - PORT=8080
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
